### ISSUE TITLE
Template fails to run on Rails 6.1.1

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#210]
```
	10: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	9: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	8: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	7: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/generators/rails/app/app_generator.rb:555:in `run_after_bundle_callbacks'
	6: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/generators/rails/app/app_generator.rb:555:in `each'
	5: from https://raw.githubusercontent.com/ackama/rails-template/main/template.rb:54:in `block in apply_template!'
	4: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/actions.rb:227:in `apply'
	3: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/actions.rb:227:in `instance_eval'
	2: from /tmp/rails-template-20210122-916210-1o34fgr/variants/frontend-base/template.rb:20:in `apply'
	1: from /home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/actions/file_manipulation.rb:274:in `gsub_file'
/home/josh/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/actions/file_manipulation.rb:274:in `binread': No such file or directory @ rb_sysopen - /home/josh/Projects/github.com/joshmcarthur/photobooth/config/webpacker.yml (Errno::ENOENT)

```

I think this is because `rails g webpacker:install` has not run before this command.

**Comment by joshmcarthur** [comment]
False alarm - I was using a too-old version of NodeJS. `asdf shell nodejs 12.8.4` resolved this
