### ISSUE TITLE
Should we use sass-embedded instead of sass by default?

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#321]
> https://www.npmjs.com/package/sass-embedded
> This package is an alternative to the [sass](https://www.npmjs.com/package/sass) package. It supports the same JS API as sass and is maintained by the same team, but where the sass package is pure JavaScript, sass-embedded is instead a JavaScript wrapper around a native Dart executable. This means sass-embedded will generally be much faster especially for large Sass compilations, but it can only be installed on the platforms that Dart supports: Windows, Mac OS, and Linux.

Using `sass-embedded` seems sensible on paper but maybe we want to trial it on a few projects first?

**Comment by eoinkelly** [comment]
I should also mention that `sass-embedded` is also fully supported by the Sass team.

> https://sass-lang.com/install
> The Sass team maintains two Node.js packages for Sass, both of which support [the standard JavaScript API](https://sass-lang.com/documentation/js-api). The [sass package](https://www.npmjs.com/package/sass) is pure JavaScript, which is a little slower but can be installed on all platforms Node.js supports. The [sass-embedded package](https://www.npmjs.com/package/sass-embedded) wraps a JS API around the Dart VM, so it's faster but only supports Windows, Mac OS, and Linux.

**Comment by eoinkelly** [comment]
The change is easy so I created a PR to verify it would pass CI.

**Comment by eoinkelly** [comment]
Hmmm CI is failing because it can't find the embedded dart environment. And it seems like `sass-embedded` might not be as "out of the box" compatible. This feels like it could be faff in future. I'm closing this for now but might pitch a future project team on trying this option on a single project to see if it's worth that potential faff.

> https://www.npmjs.com/package/sass-loader
> Warning
>
> [Sass Embedded](https://github.com/sass/embedded-host-node) is experimental and in beta, > therefore some features may not work

<details>
<summary>
Error details
</summary>
ERROR in ./app/frontend/stylesheets/application.scss (./app/frontend/stylesheets/application.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./app/frontend/stylesheets/application.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Embedded Dart Sass couldn't find the embedded compiler executable.
 @ ./app/frontend/stylesheets/application.scss
 @ ./app/frontend/packs/application.ts 11:0-40

ERROR in ./app/frontend/stylesheets/application.scss (./app/frontend/stylesheets/application.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./app/frontend/stylesheets/application.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/input.js:24:13)
    at parse (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/index.js:128:51)
 @ ./app/frontend/stylesheets/application.scss
 @ ./app/frontend/packs/application.ts 11:0-40

ERROR in ./app/frontend/stylesheets/application.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/input.js:24:13)
    at parse (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/index.js:128:51)
    at tryRunOrWebpackError (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5012:18)
    at /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/neo-async/async.js:3485:9)
    at done (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/tapable/lib/Hook.js:18:14)
    at /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:4990:43
    at symbolIterator (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/neo-async/async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/input.js:24:13)
    at parse (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/index.js:128:51)
    at Object.<anonymous> (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/app/frontend/stylesheets/application.scss:1:7)
    at /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/tapable/lib/Hook.js:14:14)
    at /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5057:39
    at tryRunOrWebpackError (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5012:18)
    at /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/neo-async/async.js:3485:9)

Generated code for /home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/app/frontend/stylesheets/application.scss
1 | throw new Error("Module build failed (from ./node_modules/css-loader/dist/cjs.js):\nError: PostCSS received undefined instead of CSS string\n    at new Input (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/input.js:24:13)\n    at parse (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/parse.js:8:15)\n    at new LazyResult (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/lazy-result.js:133:16)\n    at Processor.process (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/postcss/lib/processor.js:28:14)\n    at Object.loader (/home/runner/work/rails-template/rails-template/tmp/builds/react-typescriptdemo/node_modules/css-loader/dist/index.js:128:51)");
 @ ./app/frontend/packs/application.ts 11:0-40

1 error has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 3 errors in 7005 ms

./ci/bin/build-and-test:55:in `system': Command failed with exit 1: ./bin/ci-run (RuntimeError)
	from ./ci/bin/build-and-test:55:in `block in <main>'
	from ./ci/bin/build-and-test:53:in `chdir'
	from ./ci/bin/build-and-test:53:in `<main>'
</details>
